# Creatinga a simple function in Jac that returns a string
# and printing the returned value using the entry point.
def love_jac() -> str{
    return "with jack python becomes better.";
}

# Calling the function and printing the result, introduce main so that when you import this file it doesn't repeat
with entry__main__{
    print(f"{love_jac()}");
}

# Creating python file and importing the jac file. 
#creating first_assignment_2.py file
