#import library
import random;

walker GuessGame {
    has guess: int;

    can start with `root entry;
    can process_guess with turn entry;
}
node turn {
    has correct_number:int = random.randint(1, 100);

}


#Will run when in cli mode(not cloud mode)
with entry : __main__{
    root spawn GuessGame(3);
    root spawn GuessGame(4);
    root spawn GuessGame(5);
    root spawn GuessGame(6);
  
}